services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s"
    ports:
      - '3000:3000'
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - '6379:6379'
