services:
  - type: redis
    name: cache
    ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lfu # optional (defaults to allkeys-lru). Rails recommends allkeys-lfu as a default.
  - type: web # this example Rails service comes from https://render.com/docs/deploy-rails
    name: pakuri_ch
    runtime: ruby
    buildCommand: './bin/render-build'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: pakuri_ch
      #     property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: cache
          property: connectionString
